# steps:
# - name: 'node:14'
#   entrypoint: 'npm'
#   args: ['install']
# - name: 'node:14'
#   entrypoint: 'npm'
#   args: ['start']
#   entrypoint: 'bash'
#   args: ['-c', 'npm start & sleep 10']
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['start']
  entrypoint: 'bash'
  args: ['-c', 'npm start & sleep 10']


timeout: '1200s'